trigger: none
pr: none

pool: synkon-agent

steps:
- checkout: self
  persistCredentials: true
- task: PowerPlatformToolInstaller@2
  displayName: 'Power Platform Tool Installer '
- task: PowerPlatformExportSolution@2
  displayName: Export Solution - Unmanaged
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: $(serviceConnection)
    SolutionName: $(solution1)
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\\$(solution1).zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
- task: PowerPlatformExportSolution@2
  displayName: Export Solution - Managed
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: $(serviceConnection)
    SolutionName: $(solution1)
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\\$(solution1)_managed.zip'
    Managed: true
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
- task: PowerPlatformUnpackSolution@2
  displayName: Unpack unmanaged Solution
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\\$(solution1).zip'
    SolutionTargetFolder: '$(build.sourcesdirectory)\PowerPlatform\Solutions\$(solution1)'
    SolutionType: 'Both'
- task: CmdLine@2
  displayName: Commit to Repo
  inputs:
    script: |
      git config user.email $(Build.RequestedForEmail) 
      git config user.name "$(Build.RequestedFor)"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" fetch
      git pull https://github.com/Synkon/Nordic-ALMWS.git
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" checkout main
      git add --all
      git commit -m "$(Build.DefinitionName) $(Build.BuildNumber)"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" pull origin main
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin main
