trigger: none
pr: none

resources:
  pipelines: 
    - pipeline: buildPipeline
      source: 'Build'
      trigger: none

stages:
- stage: DeployTest
  displayName: 'Deploy to Test'
  jobs:
  - job: deployTest
    pool: synkon-agent
    steps:
    - checkout: self
    - download: buildPipeline   # pipeline resource identifier.
      artifact: drop
    - task: PowerPlatformToolInstaller@2
      displayName: 'Power Platform Tool Installer'
    - task: PowerPlatformImportSolution@2
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'NordicSummitTest'
        SolutionInputFile: '$(Pipeline.Workspace)\buildPipeline\drop\$(solution1)_managed.zip'
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        HoldingSolution: false
